########################################################
# Server configuration
########################################################
server:
  port: 8888

########################################################
# Spring Configuration
########################################################
spring:
  application:
    name: loki # Service name for Spring Cloud
    profiles:
      active: dev
    # MySQL database connection
  datasource:
    url: jdbc:mysql://localhost:3326/loki?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    username: loki
    password: Password@123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    mvc:
      pathmatch:
        # Failed to start bean 'documentationPluginsBootstrapper' in spring data rest
        # springfox3.0.0 has compatibility problem with spring boot 2.6.x
        matching-strategy: ant_path_matcher # to resolve spring fox null pointer problem

########################################################
# Mybatis-plus configuration
########################################################
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# ===== Swagger===== #
#swagger:
#  enable: true
#  application-name: ${spring.application.name}
#  application-version: 1.0
#  application-description: springfox swagger
#  try-host: http://localhost:${server.port}
#  group-name: loki
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    # http://localhost:8888/swagger-ui/index.html
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    net.geekhour.controller: info
  file:
    path: ./log
    name: ./log/loki_test.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -- [%thread] -- %-5level -- %logger{50} -- %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} == [%thread] == %-5level == %logger{50} == %msg%n"

# ===== App Config ===== #
loki:
  server:
    port: 8888
  application:
    name: loki
  application-version: 1.0
  application-description: loki service
  try-host: http://localhost:${server.port}
  group-name: loki
  app:
    jwtCookieName: loki
    jwtSecret: lokiSecretKeyGeekHourlokiSecretKeyGeekHourlokiSecretKeyGeekHourlokiSecretKeyGeekHourlokiSecretKeyGeekHourlokiSecretKeyGeekHour
    jwtExpirationMs: 86400000
    baseDirectory: /Users/yiny/workspace/vite/perseus/loki/public
  user:
    default-password: password

